/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CEmoji {
    'classes': string[];
    'emoji': string;
    'emojiLabel': string;
    'emojis': string[];
  }
  interface HueSlider {
    'hue': string;
    'max': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLCEmojiElement extends Components.CEmoji, HTMLStencilElement {}
  var HTMLCEmojiElement: {
    prototype: HTMLCEmojiElement;
    new (): HTMLCEmojiElement;
  };

  interface HTMLHueSliderElement extends Components.HueSlider, HTMLStencilElement {}
  var HTMLHueSliderElement: {
    prototype: HTMLHueSliderElement;
    new (): HTMLHueSliderElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'c-emoji': HTMLCEmojiElement;
    'hue-slider': HTMLHueSliderElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface CEmoji {
    'classes'?: string[];
    'emoji'?: string;
    'emojiLabel'?: string;
    'emojis'?: string[];
  }
  interface HueSlider {
    'hue'?: string;
    'max'?: string;
    'onInput'?: (event: CustomEvent<any>) => void;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'c-emoji': CEmoji;
    'hue-slider': HueSlider;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'c-emoji': LocalJSX.CEmoji & JSXBase.HTMLAttributes<HTMLCEmojiElement>;
      'hue-slider': LocalJSX.HueSlider & JSXBase.HTMLAttributes<HTMLHueSliderElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


